#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d Web Music Chat Code P2p Other

bspc rule -a Corebird desktop=^3 follow=on floating=on
bspc rule -a Thunar desktop=^6
bspc rule -a subl desktop=^4
bspc rule -a Firefox desktop=^1
bspc rule -a Transmission-gtk desktop=^5
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

PANEL_FONT_FAMILY="-benis-uushi-medium-r-normal--11-90-75-75-p-58-iso10646-1"
PANEL_HEIGHT=24
export PANEL_HEIGHT PANEL_FONT_FAMILY
pkill panel &
panel &
