#!/bin/sh

#
#  If you are not using one of the "normal" folders,
# but a subfolder, don't forget to add it in your xorg.conf!
#  Something like this:
#
# Section "Files"
#     FontPath "/home/anon/.fonts/MonteCarlo"
# EndSection
#

# create the pcf files
bdftopcf MonteCarloMedium.bdf > MonteCarloMedium.pcf
bdftopcf MonteCarloPanel.bdf > MonteCarloPanel.pcf

# install the fonts
mkfontdir ~/.fonts/MonteCarlo
mkfontscale ~/.fonts/MonteCarlo
xset +fp ~/.fonts/MonteCarlo
xset fp rehash
fc-cache -fv .
